name: ecoar_mobile
description: A hackathon project helping autistics to learn.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_money_formatter: ^0.8.3
  youtube_player_iframe: ^1.1.0
  cached_network_image: ^2.2.0+1
  shared_preferences: ^0.5.7+3
  cupertino_icons: ^0.1.3
  carousel_slider: ^2.2.1
  flutter_icons: ^1.1.0
  sqflite: ^1.3.1
  shimmer: ^1.1.1
  share: ^0.6.4+3
  intl: ^0.15.8
  dio: ^3.0.9
  get: ^3.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.otf
        - asset: assets/fonts/montserrat/Montserrat-Light.otf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-Medium.otf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-Semibold.otf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.otf
          weight: 700  
  assets:
    - assets/images/